language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpunit --verbose --coverage-text

matrix:
  include:
    - php: 5.3
      env: setup=lowest
    - php: 5.3
      env: setup=stable
    - php: 5.4
      env: setup=lowest
    - php: 5.4
      env: setup=stable
    - php: 5.5
      env: setup=lowest
    - php: 5.5
      env: setup=stable
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable
  allow_failures:
    - php: 5.3 # unsupported
    - php: 5.4 # unsupported
    - php: 5.5 # unsupported