language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

install:
  - composer update --prefer-dist --no-interaction --prefer-stable

script: vendor/bin/phpunit

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
